### ISSUE TITLE
wsjson.Write write in a single frame always

### ISSUE THREAD

**Issue by dar7man** [nhooyr/websocket#315] opened 2021-08-21 21:14 UTC
Hi,

I have a weird problem using this package with Binance WebSocket API. Just after I got stream subscription confirmation, connection is closed (code 1008). At the beginning I was thinking about  contacting with Binance support, but then I tried the same code but using Gorilla WebSockets package and... it worked fine.

Here is code nhooyr package version (not working):
```
package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"time"

	"nhooyr.io/websocket"
	"nhooyr.io/websocket/wsjson"
)

type subscribeMessage struct {
	Method string   `json:"method"`
	Params []string `json:"params"`
	Id     int      `json:"id"`
}

func main() {
	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
	defer cancel()

	c, _, err := websocket.Dial(ctx, "wss://stream.binance.com:9443/stream", nil)
	if err != nil {
		log.Println("dial:", err)
		return
	}
	defer func() { _ = c.Close(websocket.StatusNormalClosure, "") }()

	if err = wsjson.Write(ctx, c, subscribeMessage{
		Method: "SUBSCRIBE",
		Params: []string{"wavesbtc@depth@100ms"},
		Id:     100,
	}); err != nil {
		log.Println("write:", err)
		return
	}

	done := make(chan struct{})

	go func() {
		defer close(done)
		for {
			_, message, err := c.Read(ctx)
			if err != nil {
				log.Println("read:", err)
				return
			}
			log.Printf("recv: %s", message)
		}
	}()

	select {
	case <-interrupt:
		log.Println("interrupt")
	case <-done:
		return
	}

	err = c.Close(websocket.StatusNormalClosure, "")
	if err != nil {
		log.Println("write close:", err)
		return
	}
	<-done
}

```

And here is Gorilla version:

```
package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"time"

	"github.com/gorilla/websocket"
)

type subscribeMessage struct {
	Method string   `json:"method"`
	Params []string `json:"params"`
	Id     int      `json:"id"`
}

func main() {
	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
	defer cancel()

	c, _, err := websocket.DefaultDialer.DialContext(ctx, "wss://stream.binance.com:9443/stream", nil)
	if err != nil {
		log.Println("dial:", err)
		return
	}
	defer func() { _ = c.Close() }()
	err = c.WriteJSON(subscribeMessage{
		Method: "SUBSCRIBE",
		Params: []string{"wavesbtc@depth@100ms"},
		Id:     100,
	})
	if err != nil {
		log.Println("write:", err)
		return
	}
	done := make(chan struct{})

	go func() {
		defer close(done)
		for {
			_, message, err := c.ReadMessage()
			if err != nil {
				log.Println("read:", err)
				return
			}
			log.Printf("recv: %s", message)
		}
	}()

	select {
	case <-interrupt:
		log.Println("interrupt")
	case <-done:
		return
	}

	err = c.WriteMessage(websocket.CloseMessage, websocket.FormatCloseMessage(websocket.CloseNormalClosure, ""))
	if err != nil {
		log.Println("write close:", err)
		return
	}
	<-done
	return
}

```

Any ideas what's wrong?
Thanks!

**Comment by nhooyr** [comment] 2021-08-21 23:01
Hi @dar7man 

Yea super weird looks perfect to me. Can you try the dev branch as well? Just `go get nhooyr.io/websocket@dev`

**Comment by dar7man** [comment] 2021-08-22 05:02
Hi @nhooyr 

Thanks for quick response. I tried dev brach, but not luck. Still doesn't work.

**Comment by nhooyr** [comment] 2021-08-23 12:55
Huh, yea that's really bizarre.

Only difference between I see is the `Id` used in this library's demo is `100` but for Gorilla it's `1`. Could that be the reason?

**Comment by dar7man** [comment] 2021-08-23 14:33
No, unfortunately. This number doesn't matter. Looks like something different must be sent using your package. I don't know, maybe packet sniffing/monitoring could help with investigation? I now that Windows 10 had build in such a tool (pktmon.exe). Maybe I'll try some day to use it and try to find a difference.

**Comment by dar7man** [comment] 2021-08-25 09:31
Got some news here. Looks like something weird is happening in **wsjson.Write()**. 
Replacing wsjson.Write() with my own json marshaling and plain Write() solves the issue:

```
msg, err := json.Marshal(subscribeMessage{
  Method: "SUBSCRIBE",
  Params: []string{"wavesbtc@depth@100ms"},
  Id:     100,
})
if err != nil {
  log.Println("write:", err)
  return
}
if err = c.Write(ctx, websocket.MessageText, msg); err != nil {
  log.Println("write:", err)
  return
}

```

And it works like a charm.

**Comment by XanderShum** [comment] 2021-11-09 16:25
I ran into the same problem, thank you for your help.

**Comment by zeroallox** [comment] 2022-07-03 18:33
I'm experiencing this same issue while using normal `Write()`. Have not even tried `wsjson.Write()` or any of the util methods. Using main branch / latest release.

**Comment by elee1766** [comment] 2022-11-11 02:47
my guess is the actual "issue" is that the "json.Encoder" appends \n at the end of json messages. there's a long discussion on some issue in golang about it but it's basically so that you can use a json.Encoder with like a file and it will publish one json entry per line. https://cs.opensource.google/go/go/+/refs/tags/go1.19.3:src/encoding/json/stream.go;l=217 

the issue is some json rest and json rpc servers dont like the newline. especially ones not written in go.   

the most sane way i know how to fix this is to wrap with a write method that removes the last byte if it is a newline, since encoding/json writes the entire encoded json buffer to the underlying writer at once.

```
import "io"

// usage: json.NewEncoder(&noTrailingNewlineWriter{w})
type noTrailingNewlineWriter struct {
  w io.Writer
}

func (n *noTrailingNewlineWriter) Write(xs []byte) (int, error) {
  if xs[len(xs)-1] == '\n' {
    xs = xs[:len(xs)-1]
  }
  return n.w.Write(xs)
}
```

**Comment by SirGreyK** [comment] 2023-02-19 12:22
> PS. Oh! One more thing to mention: this workaround only works with _dev branch_!

Is Dev a reliable branch to use in production?

I would like to use this library, as gorilla is archived. But I have concerns about the reliability of the Dev branch.

Maybe I should use Gorilla for now and wait for this problem to be resolved?

Do you have any advice?

**Comment by nhooyr** [comment] 2023-03-05 21:28
Yea so binance doesn't support fragmented websocket frames for some reason. This library normally writes fragmented frames but the dev branch fixes it to not with `Write`. So after dev is merged into master I'll close this.

**Comment by timo-klarshift** [comment] 2023-05-02 12:44
can it be closed?

**Comment by dar7man** [comment] 2023-05-04 05:49
Sure

wt., 2 maj 2023, 14:44 użytkownik Timo Friedl ***@***.***>
napisał:

**Comment by nhooyr** [comment] 2023-10-13 07:15
Actually I took another look at the code and v1.8.7 includes the fix to change `Write` to guarantee writing a single frame but only if compression is disabled.

So the fix here is don't use `wsjson` as that will not write the result in a single frame but also disable compression with v1.8.7.

v1.8.8 will disable compression by default so it won't be an issue in the next release.

Sorry for the confusion.

**Comment by nhooyr** [comment] 2023-10-13 07:17
Actually in v1.8.8 I'll change `wsjson.Write` to just make it work. The reason it doesn't is because I was trying to be clever and use `json.Encoder` instead of `json.Marshal` as encoder reuses the buffer it writes the JSON too whereas json.Marshal always does an allocation.

**Comment by nhooyr** [comment] 2023-10-13 07:18
But I can still use `json.Encoder` and have it call `Write` on the connection instead of `Writer`. So this will be fixed next release.

**Comment by nhooyr** [comment] 2023-10-13 09:07
Done in dev.

**Closed by nhooyr** 2023-10-13 09:07 UTC
Labels: enhancement
