### ISSUE TITLE
go-beta: panic: interface conversion: context.Context is *context.timerCtx, not *context.emptyCtx

### ISSUE THREAD

**Issue by thedaneeffect** [nhooyr/websocket#274] opened 2020-12-26 02:24 UTC
Hi there, I seem to be having an issue using this module. It seems both the client and server get this panic immediately. Here's some important information:

go version go1.16beta1 windows/amd64
Server target: **native**
Client target: **wasm**

https://github.com/nhooyr/websocket/blob/v1.8.6/conn_notjs.go#L163

 Here are my backend/frontend files:

console
```text
panic: interface conversion: context.Context is *context.timerCtx, not *context.emptyCtx

goroutine 19 [running]:
nhooyr.io/websocket.(*Conn).timeoutLoop(0xc0000c2000)
	C:/Users/dane/go/pkg/mod/nhooyr.io/websocket@v1.8.6/conn_notjs.go:160 +0x449
created by nhooyr.io/websocket.newConn
	C:/Users/dane/go/pkg/mod/nhooyr.io/websocket@v1.8.6/conn_notjs.go:114 +0x41b

Process finished with exit code 2
```

backend
```go
package main

import (
	"context"
	"log"
	"net/http"
	"time"

	"nhooyr.io/websocket"
	"nhooyr.io/websocket/wsjson"
)

func main() {
	err := http.ListenAndServe(":10000", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		c, err := websocket.Accept(w, r, nil)

		if err != nil {
			println(err)
		}

		defer c.Close(websocket.StatusInternalError, "the sky is falling")

		ctx, cancel := context.WithTimeout(r.Context(), time.Second*10)
		defer cancel()

		var v interface{}
		err = wsjson.Read(ctx, c, &v)

		if err != nil {
			println(err)
		}

		log.Printf("received: %v", v)

		c.Close(websocket.StatusNormalClosure, "")
	}))

	if err != nil {
		panic(err)
	}
}
```

frontend
```go
package main

import (
	"context"
	"time"

	"nhooyr.io/websocket"
	"nhooyr.io/websocket/wsjson"
)

func main() {
	ctx, cancel := context.WithTimeout(context.Background(), time.Minute)
	defer cancel()

	c, _, err := websocket.Dial(ctx, "ws://localhost:10000", nil)

	if err != nil {
		panic(err)
	}

	defer c.Close(websocket.StatusInternalError, "the sky is falling")

	err = wsjson.Write(ctx, c, "hello, world!")

	if err != nil {
		panic(err)
	}

	c.Close(websocket.StatusNormalClosure, "")
}
```

**Comment by nhooyr** [comment] 2020-12-26 08:15
> go version go1.16beta1 windows/amd64

Looks like `context.Background().Done()` panics on go1.16 for some reason?

Can you try non beta go?

**Comment by nhooyr** [comment] 2020-12-26 08:17
Can you post the full output? There should be more.

**Comment by notmyalias** [comment] 2020-12-27 03:59
I am also running into this issue trying to build this in dev. on Go 1.16 beta - no issues on Go 1.15.5 which I am currently running in prod.

```
panic: interface conversion: context.Context is *context.timerCtx, not *context.emptyCtx

goroutine 36 [running]:
nhooyr.io/websocket.(*Conn).timeoutLoop(0xc000446000)
        /Users/alias/go/pkg/mod/nhooyr.io/websocket@v1.8.6/conn_notjs.go:160 +0x429
created by nhooyr.io/websocket.newConn
        /Users/alias/go/pkg/mod/nhooyr.io/websocket@v1.8.6/conn_notjs.go:114 +0x413
exit status 2
```

No other output beyond this. Please let me know if there's anything else that I could offer to help.

Thanks in advance!

**Comment by nhooyr** [comment] 2020-12-27 14:06
Can confirm.

Tests fail with `go1.16beta1` but I confirmed this has been fixed in Go's `master` branch and so will be fixed in the next release.

**Closed by nhooyr** 2020-12-27 14:06 UTC
Labels: wontfix

**Comment by nhooyr** [comment] 2020-12-27 14:11
Weird I can't find any related issue/commit/PR on the Go repo.

**Comment by nhooyr** [comment] 2020-12-27 14:23
Looks like it was https://github.com/golang/go/issues/43292

The tests fail on commits prior but pass after the linked commit!

**Comment by nhooyr** [comment] 2020-12-27 14:24
https://github.com/golang/go/commit/89b44b4e2bb2f88474d6b8476f5c28ea2aea9b28
