### ISSUE TITLE
Gin compatabilty

### ISSUE THREAD

**Issue by nmec** [nhooyr/websocket#166] opened 2019-10-25 13:59 UTC
I'm trying to integrate this into my existing app which is using the Gin framework, but I'm unable to establish a connection from the browser. Any ideas how I can get this working?

**Server**
```go
package main

import (
	"context"
	"log"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"nhooyr.io/websocket"
	"nhooyr.io/websocket/wsjson"
)

func main() {
	router := gin.New()

	router.GET("/ws", handler)

	router.Run(":7000")
}

func handler(c *gin.Context) {
	log.Println("upgrading")
	conn, wsErr := websocket.Accept(c.Writer, c.Request, &websocket.AcceptOptions{
		InsecureSkipVerify: true,
	})

	if wsErr != nil {
		c.AbortWithError(http.StatusInternalServerError, wsErr)
		return
	}

	defer conn.Close(websocket.StatusInternalError, "Closed unexepetedly")

	log.Println("ready")

	ctx, cancel := context.WithTimeout(c.Request.Context(), time.Minute)
	defer cancel()
	ctx = conn.CloseRead(ctx)

	tick := time.NewTicker(time.Second * 5)
	defer tick.Stop()

	for {
		select {
		case <-ctx.Done():
			log.Println("done")
			conn.Close(websocket.StatusNormalClosure, "")
			return
		case <-tick.C:
			writeErr := wsjson.Write(ctx, conn, map[string]interface{}{
				"msg": "hello",
			})
			if writeErr != nil {
				log.Println(writeErr)
				return
			}
		}
	}
}
```

**Client**
```js
const ws = new WebSocket('ws://localhost:7000/ws');
ws.onopen = console.log;
ws.onmessage = console.log;
```

**JS Error**
`WebSocket connection to 'ws://localhost:7000/ws' failed: Error during WebSocket handshake: net::ERR_INVALID_HTTP_RESPONSE`

**Server logs**
```logs
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /ws                       --> main.handler (1 handlers)
[GIN-debug] Listening and serving HTTP on :7000
2019/10/25 15:17:49 upgrading
2019/10/25 15:17:49 ready
2019/10/25 15:17:54 done
```

**Comment by nhooyr** [comment] 2019-10-25 14:16
What does the Go program log?

**Comment by nhooyr** [comment] 2019-10-25 14:17
Also, print wsErr.

**Comment by nmec** [comment] 2019-10-25 14:20
Thanks for the speedy reply - I've updated the description with the server logs.

**Comment by nhooyr** [comment] 2019-10-25 14:23
Mhmm. I believe the issue is that gin doesn't allow writing a response before hijacking the connection the way net/http does. Gorilla works because it hijacks first, then writes the handshake response directly to the tcp connection. We could do this as well but it'd be janky.

What do you get in the network tab of the browser? What does the HTTP response look like?

**Comment by nmec** [comment] 2019-10-25 14:25
HTTP Request:
![image](https://user-images.githubusercontent.com/943232/67578978-759f0e00-f73b-11e9-8386-9ee4e5699073.png)
HTTP Response:
![image](https://user-images.githubusercontent.com/943232/67579011-8e0f2880-f73b-11e9-98c2-c889f9e49bca.png)

**Comment by nhooyr** [comment] 2019-10-25 14:27
Got it, what does the headers tab look like for the response?

**Comment by nmec** [comment] 2019-10-25 14:28
No response headers are shown, only the request.

**Comment by nhooyr** [comment] 2019-10-25 14:34
Cool, lines up with my reasoning.

Looks like gin deviates from net/http for some reason. Have to call an additional WriteHeaderNow method to write the header.

https://github.com/gin-gonic/gin/blob/094f9a9105f8e7b971a01a64677eef5a1f7bcd9b/response_writer.go#L69

Opened https://github.com/gin-gonic/gin/issues/2108

Will fix tonight.

**Comment by nmec** [comment] 2019-10-25 14:38
Amazing, thanks so much for the quick responses.

**Comment by nmec** [comment] 2019-10-25 14:50
Not sure if this is of use to you to fix the issue, but I just tried [gobwas/ws](https://github.com/gobwas/ws) for the heck of it and it works perfectly:

```go
package main

import (
	"encoding/json"
	"log"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/gobwas/ws"
	"github.com/gobwas/ws/wsutil"
)

func main() {
	router := gin.Default()

	router.GET("/ws", handler)

	router.Run(":7000")
}

func handler(c *gin.Context) {
	log.Println("upgrading")
	conn, _, _, err := ws.UpgradeHTTP(c.Request, c.Writer)
	if err != nil {
		log.Println(err)
	}

	log.Println("ready")

	go func() {
		tick := time.NewTicker(time.Second * 5)
		defer tick.Stop()
		defer conn.Close()

		for {
			select {
			case <-tick.C:
				log.Println("tick")
				data, _ := json.Marshal(map[string]interface{}{
					"msg": "hello",
				})

				err = wsutil.WriteServerMessage(conn, ws.OpText, data)
				if err != nil {
					log.Println(err)
				}

			}
		}
	}()
}
```

**Comment by nhooyr** [comment] 2019-10-25 15:00
If you add `w.(interface{ WriteHeaderNow() }.WriteHeaderNow())` on this line https://github.com/nhooyr/websocket/blob/8bf88772e1209d96a00bc38276cda458661ebe2b/handshake.go#L143 things should work. Could you test it?

**Comment by nhooyr** [comment] 2019-10-25 15:00
gohack may be helpful. https://github.com/rogpeppe/gohack

**Comment by nhooyr** [comment] 2019-10-29 03:39
Best to fix this in gin by making the response writer Hijack method flush any written header.

**Comment by nhooyr** [comment] 2019-11-01 21:26
See https://github.com/gin-gonic/gin/pull/2120

**Comment by elnappo** [comment] 2020-05-07 12:51
Did I miss the oblivious solution here? Not sure how to fix that. Do I really need to use gohack, because this would be a very ugly way? Why did you close your pull request in gin-gonic/gin?

**Comment by nmec** [comment] 2020-05-07 13:40
In the end I ended up using [gobwas/ws](https://github.com/gobwas/ws) over this library, since my implementation shared above worked with Gin whilst this was awaiting a fix upstream. It's a little bit lower level than this library, but with the util package it's not too much extra work and you get a better understanding of how the underlaying protocol is working. Sorry if that's not much help for your immediate problem!

**Comment by nhooyr** [comment] 2020-05-07 15:53
There are a ton of unmerged PRs and issues on gin. I'd recommend against using it and I closed that PR because it didn't seem to have a chance of getting merged.

However, given it's prevalence in the ecosystem, I'll add a patch here to make it work :)

**Comment by nhooyr** [comment] 2020-05-07 17:56
Yea my bad I meant to add a fix here but I guess it slipped.

See https://github.com/gin-gonic/gin/issues/2108

**Comment by nhooyr** [comment] 2020-05-10 12:07
Master works now on Gin, will tag a release EOD :)

**Closed** 2020-05-10 12:07 UTC
Labels: enhancement

**Comment by elnappo** [comment] 2020-05-11 06:48
Thank you! :)

**Comment by nhooyr** [comment] 2020-05-18 04:58
Sorry for the delay, tagged v1.8.6 today!
